@extends('home.template')
@section('content')

    <style>
        .single-course-list .course-image a img {
            width: 100px !important;
        }
    </style>

    <!-- Page Banner Start -->
    <div class="section page-banner-section" style="background-color: #FACB27;">
        <div class="shape-3"></div>
        <div class="container">
            <div class="page-banner-wrap">
                <div class="row">
                    <div class="col-lg-8">
                        <br />
                        <h1>Terms Of Service</h1>

                    </div>

                </div>
            </div>
        </div>
    </div>
    <!-- Page Banner End -->


    <!-- Course List Start -->
    <div class="section section-padding">
        <div class="container">

            <!-- Course List Wrapper Start -->
            <div class="course-list-wrapper">
                <div class="row">
                    <p style="color:#ffffff;background-color:#ffffff;"><span style="color:#262626;font-size:13pt;">SPEAKEDE TERMS OF SERVICE</span></p>
                    <p style="color:#ffffff;background-color:#ffffff;"><span style="color:#515164;font-size:10.5pt;">(Updated on August, 2023)</span></p>
                    <p style="color:#ffffff;background-color:#ffffff;"><br></p>
                    <hr>
                    <p><br></p>
                    <p style="color:#ffffff;background-color:#ffffff;"><span style="color:#515164;font-size:10.5pt;">Please read these Speakede Terms of Service (the &quot;Speakede Terms&apos;&apos; or &quot;Speakede Terms of Service&quot;) carefully as they govern (i) your access to and use of our Sites, (ii) your access to and use of our Applications, or (iii) your access to and use of our services that link to or reference these Speakede Terms, and contain important information about your legal rights, remedies and obligations. The Site, Application and other Speakede services together are hereinafter collectively referred to as the &quot;Speakede Platform&apos;&apos;. By accessing or using the Speakede Platform, you are agreeing to these Speakede Terms and concluding a legally binding contract with Speakede, whether or not you become a registered user of the Speakede Platform. Certain areas of the Speakede Platform may have different terms and conditions, standards, guidelines, or policies posted or may require you to agree with and accept additional terms and conditions. If there is a conflict between these Speakede Terms and the terms and conditions posted for a specific area of the Speakede Platform, the terms and conditions that are specific to that area will take precedence with respect to your use of, or access to, that area of the Speakede Platform.</span></p>
                    <p style="color:#ffffff;background-color:#ffffff;"><span style="color:#515164;font-size:10.5pt;">You may be referred to in these Speakede Terms as &quot;you&quot; or &quot;your&quot;, or may be referred to specifically in your applicable role as a Company or an Authorized User (each as defined below). If you are entering into this Speakede Terms on behalf of a company or other legal entity (such company or legal entity, the &quot;Company&quot;), this Speakede Terms shall be a binding agreement between Speakede and the Company that you represent, and you represent that you have the authority to bind such Company, its users, and its affiliates to this Speakede Terms. In that case, the terms &quot;you&quot; or &quot;your&quot; shall also refer to such an entity, its users, and its affiliates, as applicable. If you do not have such authority, or if you do not agree with these Speakede Terms, you may not use the Service. If you are entering into this Speakede Terms as an individual and not on behalf of a company or other legal entity, this Speakede Terms shall be a binding agreement between Speakede and you personally. You acknowledge that this Speakede terms is a contract between you and Speakede, even though it is electronic and is not physically signed by you and Speakede, and it governs your use of the Service.</span></p>
                    <p style="color:#ffffff;background-color:#ffffff;"><span style="color:#515164;font-size:10.5pt;">You represent that you have read and understood our privacy policy (&quot;Privacy Policy&quot;), which is available at&nbsp;</span><a href="https://www.italki.com/privacy"><u><span style="color:#59789b;font-size:10.5pt;">https://www.Speakede.com/privacy</span></u></a><span style="color:#515164;font-size:10.5pt;">. Note that we may disclose information about you to third parties if we have a good faith belief that such a disclosure is reasonably necessary to (i) take action regarding suspected illegal activities; (ii) enforce or apply Speakede Terms or other Speakede Policies (as defined below); (iii) comply with legal process or other government inquiry, such as a search warrant, subpoena, statute, judicial proceeding or other legal process served on us; or (iv) protect our rights, reputation, and property or that of our users, affiliates or the public. Our (a) Tutor policy, which is available at&nbsp;</span><a href="https://www.italki.com/instructorterms"><u><span style="color:#59789b;font-size:10.5pt;">https://www.Speakede.com/instructorterms</span></u></a><span style="color:#515164;font-size:10.5pt;">&nbsp;(the &quot;Tutor Policy&quot;); (b) payment policy, which is available at&nbsp;</span><a href="https://www.italki.com/paymentterms"><u><span style="color:#59789b;font-size:10.5pt;">https://www.Speakede.com/paymentterms</span></u></a><span style="color:#515164;font-size:10.5pt;">&nbsp;(the &quot;Payment Policy&quot;); (c) community policy, which is available at&nbsp;</span><a href="https://www.italki.com/communitypolicy"><u><span style="color:#59789b;font-size:10.5pt;">https://www.Speakede.com/communitypolicy</span></u></a><span style="color:#515164;font-size:10.5pt;">&nbsp;(the &quot;Community Policy&quot;), and (d) copyright policy, which is available at&nbsp;</span><a href="https://www.italki.com/copyrightpolicy"><u><span style="color:#59789b;font-size:10.5pt;">https://www.Speakede.com/copyrightpolicy</span></u></a><span style="color:#515164;font-size:10.5pt;">&nbsp;(the &quot;Copyright Policy&quot;, together with Privacy Policy, Tutor Policy, Payment Policy, Community Policy and Copyright Policy, the &quot;Speakede Polices&quot;), to the extent applicable to your use of the Speakede Platform are incorporated by reference into these Speakede Terms.</span></p>
                    <p style="color:#ffffff;background-color:#ffffff;"><span style="color:#515164;font-size:10.5pt;">Do not access or use the Speakede Platform if you are unwilling or unable to be bound by these Speakede Terms.</span></p>
                    <p style="color:#ffffff;background-color:#ffffff;"><br></p>
                    <hr>
                    <p><br></p>
                    <h5 style="color:#ffffff;background-color:#ffffff;"><strong><span style="color:#313140;font-size:15pt;">1. Definitions</span></strong></h5>
                    <p style="color:#ffffff;background-color:#ffffff;"><span style="color:#515164;font-size:10.5pt;">&quot;Applications&quot; means the applications for mobile, tablet, and other smart devices and application program interfaces provided by Speakede, including but not limited to the mobile applications entitled as &quot;Speakede&quot;.</span></p>
                    <p style="color:#ffffff;background-color:#ffffff;"><span style="color:#515164;font-size:10.5pt;">&quot;Speakede&quot;, &quot;we&quot;, &quot;us&quot;, or &quot;our&quot; means (i) Speakede Inc., with respect to Members that access and use of the Speakede Service; with respect to Members that access and use of the &nbsp;Service.</span></p>
                    <p style="color:#ffffff;background-color:#ffffff;"><span style="color:#515164;font-size:10.5pt;">&quot;Speakede Content&quot; &nbsp;means any content that Speakede creates and makes available in connection with the Speakede Platform, including proprietary Speakede content and any content licensed or authorized for use by or through Speakede from a third party, but excluding Member Content.</span></p>
                    <p style="color:#ffffff;background-color:#ffffff;"><span style="color:#515164;font-size:10.5pt;">&quot;Speakede Product&quot; means the Application(s) of &quot;Speakede&quot;, the Site &quot;</span><a href="https://www.italki.com/"><u><span style="color:#59789b;font-size:10.5pt;">www.Speakede.com</span></u></a><span style="color:#515164;font-size:10.5pt;">&quot; and any website operated by Speakede Inc..</span></p>
                    <p style="color:#ffffff;background-color:#ffffff;"><span style="color:#515164;font-size:10.5pt;">&quot;Member Content&quot; means all content, such as text, photos, audio, video, or other materials and information, that a Member posts, uploads, publishes, submits, transmits, includes in their Member profile.</span></p>
                    <p style="color:#ffffff;background-color:#ffffff;"><span style="color:#515164;font-size:10.5pt;">&quot;Sites&quot; means Speakede&rsquo;s websites, including but not limited to&nbsp;</span><a href="https://www.italki.com/"><u><span style="color:#59789b;font-size:10.5pt;">www.Speakede.com</span></u></a></p>
                    <p style="color:#ffffff;background-color:#ffffff;"><span style="color:#515164;font-size:10.5pt;">&quot;Learner&quot; means a Member that purchases Tutor Services.</span></p>
                    <p style="color:#ffffff;background-color:#ffffff;"><span style="color:#515164;font-size:10.5pt;">&quot;Tutor&quot; means a Member that offers and delivers Tutor Services.</span></p>
                    <p style="color:#ffffff;background-color:#ffffff;"><span style="color:#515164;font-size:10.5pt;">&quot;Tutor Services&quot; means all services delivered by Tutors as described in the Tutor Policy, including but not limited to paid lessons, packages and other services rendered where Speakede Credits (as defined in Payment Policy) are exchanged.</span></p>
                    <h5 style="color:#ffffff;background-color:#ffffff;"><strong><span style="color:#313140;font-size:15pt;">2. Relationship</span></strong></h5>
                    <p style="color:#ffffff;background-color:#ffffff;"><span style="color:#515164;font-size:10.5pt;">The Speakede Platform is an online venue for language learning where registered users (&quot;Members&quot;) may use our Connection Services and Payment Services to directly interact with one another. You understand and agree that Speakede is not a party to any agreements entered into between Learners and Tutors or between Members, nor is Speakede a language services broker or agent. Speakede has no control over the conduct of Learners, Tutors, Members or other users of the Speakede Platform or over any services provided by Tutors or other Members over the Speakede Platform, and disclaims all liability in this regard to the maximum extent permitted by law.</span></p>
                    <p style="color:#ffffff;background-color:#ffffff;"><span style="color:#515164;font-size:10.5pt;">If you choose to teach on the Speakede Platform, you understand and agree that your relationship with Speakede is limited to being a Member and an independent, third-party contractor, and not an employee, agent, joint venturer or partner of Speakede for any reason, and you act exclusively on your own behalf and for your own benefit, and not on behalf of or for the benefit of Speakede. Speakede does not control, and has no right to control, your listing, your activities associated with your profile or listed services, or any other matters related to any services that you provide. As a Member you agree not to do anything to create a false impression that you are endorsed by, partnering with, or acting on behalf of or for the benefit of Speakede, including by using any Speakede intellectual property in an unauthorized or in appropriate manner.</span></p>
                    <h5 style="color:#ffffff;background-color:#ffffff;"><strong><span style="color:#313140;font-size:15pt;">3. Modification</span></strong></h5>
                    <p style="color:#ffffff;background-color:#ffffff;"><span style="color:#515164;font-size:10.5pt;">Speakede reserves the right, at its sole discretion, to modify the Speakede Platform and to modify these Speakede Terms, at any time and without prior notice. If we modify these Speakede Terms, we will either post the modification on the Sites and the Applications or otherwise provide you with notice of the modification. We will also update the &quot;Updated&quot; date at the top of these Speakede Terms. By continuing to access or use the Speakede Platform after we have posted a modification on the Sites and the Applications or have provided you with notice of a modification, you are indicating that you agree to be bound by the modified Speakede Terms. If the modified Speakede Terms are not acceptable to you, your only recourse is to cease using the Speakede Platform.</span></p>
                    <h5 style="color:#ffffff;background-color:#ffffff;"><strong><span style="color:#313140;font-size:15pt;">4. Eligibility</span></strong></h5>
                    <p style="color:#ffffff;background-color:#ffffff;"><span style="color:#515164;font-size:10.5pt;">The Speakede Platform is available only to, and may only be used by, individuals who are 18 years and older who can form legally binding contracts under applicable law.</span></p>
                    <p style="color:#ffffff;background-color:#ffffff;"><span style="color:#515164;font-size:10.5pt;">WHILE WE USE GOOD FAITH EFFORTS TO CONFIRM THAT EACH TEACHER ON THE SPEAKEDE PLATFORM IS PROFESSIONAL, WE ARE NOT ABLE TO PROVIDE ANY ASSURANCES REGARDING THE CHARACTER OR OTHER QUALITIES OF TEACHERS AND THE ACCURACY OF THE INFORMATION TEACHERS PROVIDE VIA THE SPEAKEDE PLATFORM. WHEN INTERACTING WITH OTHER MEMBERS YOU SHOULD EXERCISE CAUTION AND COMMON SENSE TO PROTECT YOUR PERSONAL SAFETY AND PROPERTY, JUST AS YOU WOULD WHEN INTERACTING WITH OTHER PERSONS WHOM YOU DON&rsquo;T KNOW. NEITHER SPEAKEDE NOR ITS AFFILIATES OR LICENSORS IS RESPONSIBLE FOR THE CONDUCT, WHETHER ONLINE OR OFFLINE, OF ANY MEMBERS OF THE SPEAKEDE PLATFORM. SPEAKEDE AND ITS AFFILIATES AND LICENSORS WILL NOT BE LIABLE FOR ANY CLAIM, INJURY OR DAMAGE ARISING IN CONNECTION WITH YOUR USE OF THE SPEAKEDE PLATFORM.</span></p>
                    <h5 style="color:#ffffff;background-color:#ffffff;"><strong><span style="color:#313140;font-size:15pt;">5. Description of Services</span></strong></h5>
                    <h6 style="color:#ffffff;background-color:#ffffff;"><strong><span style="color:#313140;font-size:12pt;">5.1 Speakede Services</span></strong></h6>
                    <p style="color:#ffffff;background-color:#ffffff;"><span style="color:#515164;font-size:10.5pt;">Speakede&rsquo;s services includes:</span></p>
                    <ol>
                        <li style="list-style-type:decimal;color:#515164;font-size:10.5pt;">
                            <p style="color:#ffffff;background-color:#ffffff;"><span style="color:#515164;font-size:10.5pt;">Connection Services. Speakede provides Members with access to and use of the Speakede Platform, which is an online venue where (a) Members can upload, submit, store, send and receive content related to language learning; (b) Members can conduct searches, connect with, choose, and engage each other for the purposes of language learning and instant language practice; (c) Learners can conduct searches, connect with, choose, and engage Tutors directly for language instruction and Tutor Services; (d) Tutors can advertise their capabilities, respond to inquiries, connect with and engage Learners to provide them with their Tutor Services (collectively, &quot;Connection Services&quot;). For the avoidance of doubt, in providing the Connection Services, Speakede only provides the venue for Members, including Learners and Tutors, to find and contract with each other, and Speakede does not take part in direct interactions between Members.</span></p>
                        </li>
                        <li style="list-style-type:decimal;color:#515164;font-size:10.5pt;">
                            <p style="color:#ffffff;background-color:#ffffff;"><span style="color:#515164;font-size:10.5pt;">Payment Services. For Learners and Tutors, Speakede also provides certain payment processing services, credit purchase and payment tools, dispute resolution procedures and assistance, and other services in accordance with Speakede&rsquo;s Payment Policy (collectively, &quot;Payment Services&quot;). Payment Services do not include Connection Services.</span></p>
                        </li>
                        <li style="list-style-type:decimal;color:#515164;font-size:10.5pt;">
                            <p style="color:#ffffff;background-color:#ffffff;"><span style="color:#515164;font-size:10.5pt;">Business Services. If a Member is a Company, such Member may authorize additional individuals and/or their employees (the &quot;Employees&quot;) to use of the Speakede Platform, including but not limited to the Connection Services and Payment Services. The Company may (i) track Employees&rsquo; completed lessons, (ii) add or remove any Employees from access to or the use of Speakede Platform, (iii) control, refill or shift their Speakede credits balances within such Company&rsquo;s Speakede Account (as defined below). The Company may also review the Employees&rsquo; language learning performance report through its Speakede Account. For the avoidance of doubt, an Employee shall be considered as a &quot;Learner&quot;.</span></p>
                        </li>
                    </ol>
                    <h6 style="color:#ffffff;background-color:#ffffff;"><strong><span style="color:#313140;font-size:12pt;">5.2 Tutor Services</span></strong></h6>
                    <p style="color:#ffffff;background-color:#ffffff;"><span style="color:#515164;font-size:10.5pt;">Tutors may provide certain Tutor Services through the Speakede Platform. If you are accepted to be a Tutor, you agree to Speakede&apos;s Tutor Policy. All Members hereby acknowledge that the Tutor Services are solely provided by Tutors and are not provided by Speakede. Speakede&rsquo;s responsibility with respect to Tutor Services is limited to facilitating the availability of the Speakede Platform.</span></p>
                    <h5 style="color:#ffffff;background-color:#ffffff;"><strong><span style="color:#313140;font-size:15pt;">6. Speakede Account</span></strong></h5>
                    <h6 style="color:#ffffff;background-color:#ffffff;"><strong><span style="color:#313140;font-size:12pt;">6.1 Account Registration</span></strong></h6>
                    <p style="color:#ffffff;background-color:#ffffff;"><span style="color:#515164;font-size:10.5pt;">In order to use many of the features that are offered through the Speakede Platform, you must create an account (&quot;Speakede Account&quot;) and become a Member.</span></p>
                    <p style="color:#ffffff;background-color:#ffffff;"><span style="color:#515164;font-size:10.5pt;">Your Speakede Account is for personal, non-commercial use only, provided that, if you are creating an Speakede Account on behalf of a Company, you may authorize their Employees to use of the Speakede Platform. To create an Speakede Account, you must be eligible to use the Speakede Platform for which you are registering, be a resident of a country where use of the Speakede Platform is permitted, have a valid email address, have a valid mobile phone number (if applicable) and provide truthful and accurate information. You may not impersonate someone else, provide an email address or mobile phone number other than your own or create multiple Speakede Accounts. You may choose to show a pseudonym to other Members, but please remember that others may still be able to identify you if, for example, you include identifying information during your use of the Speakede Platform, use the same Speakede Account information on other sites or allow other sites to share information about you with us. Please read our Privacy Policy for more information.</span></p>
                    <p style="color:#ffffff;background-color:#ffffff;"><span style="color:#515164;font-size:10.5pt;">You may not have more than one (1) active Speakede Account. You agree to provide accurate, current and complete information during the registration process and to update such information to keep it accurate, current and complete. Speakede reserves the right to suspend or terminate your Speakede Account and your access to the Speakede Platform if you create more than one (1) Speakede Account, or if any information provided during the registration process or thereafter proves to be inaccurate, fraudulent, not current, incomplete, or otherwise in violation of these Speakede Terms.</span></p>
                    <p style="color:#ffffff;background-color:#ffffff;"><span style="color:#515164;font-size:10.5pt;">In addition, to create an Speakede Account, Speakede may require you to select a username and password. You acknowledge that you shall be responsible for ensuring that any username you select does not infringe any third-party rights and is not otherwise unlawful. Speakede may refuse to grant you a username in Speakede&rsquo;s sole discretion for any reason including if the proposed username impersonates or misleadingly implies an association with the persona of another person or entity, is or may be illegal, is or may be protected by trademark or other proprietary rights, is vulgar or otherwise offensive, or may cause confusion, or for any other reason as determined by Speakede in Speakede&rsquo;s sole discretion. Your selection and use of a specific username do not convey any ownership or rights in that username and Speakede reserves the right to revoke and/or reassign that username in Speakede&rsquo;s sole discretion. You understand and agree that Speakede reserves the right to change, remove, alter or delete any username, with or without prior notice to you, at any time and for any reason in Speakede&rsquo;s sole discretion. YOU ARE ENTIRELY RESPONSIBLE FOR MAINTAINING THE CONFIDENTIALITY OF YOUR USERNAME AND PASSWORD AND ALL ACCESS TO AND USE OF YOUR SPEAKEDE ACCOUNT, INCLUDING ANY AND ALL ACTIVITIES (INCLUDING USE OF THE SPEAKEDE PLATFORM, AS APPLICABLE) THAT ARE CONDUCTED THROUGH THE USE OF YOUR USERNAME AND PASSWORD WHETHER OR NOT AUTHORIZED BY YOU. YOUR SPEAKEDE ACCOUNT MAY BE SUSPENDED OR TERMINATED IF SOMEONE ELSE USES YOUR SPEAKEDE ACCOUNT TO ENGAGE IN ACTIVITY THAT VIOLATES THESE SPEAKEDE TERMS.</span></p>
                    <p style="color:#ffffff;background-color:#ffffff;"><span style="color:#515164;font-size:10.5pt;">You agree to notify Speakede immediately of any unauthorized use of your Speakede Account. We reserve the right to close your Speakede Account at any time if you violate these Speakede Terms or if we otherwise have a legitimate interest to do so, such as complying with a legal or regulatory obligation.</span></p>
                    <h6 style="color:#ffffff;background-color:#ffffff;"><strong><span style="color:#313140;font-size:12pt;">6.2 Third-Party Account</span></strong></h6>
                    <p style="color:#ffffff;background-color:#ffffff;"><span style="color:#515164;font-size:10.5pt;">You can also register to become a Member by logging into your account with certain third-party social networking sites (&quot;SNS&quot;) including, but not limited to, Facebook and WeChat (each such account is a &quot;Third-Party Account&quot;), through our Sites or Applications. Unless you add your email address or phone number and set up a password for such account, if a Third-Party Account or associated service becomes unavailable or Speakede&apos;s access to such Third-Party Account is terminated by you or the third-party service provider, then you are no longer be able to log into any Speakede Platform through such Third-Party Account.</span></p>
                    <h6 style="color:#ffffff;background-color:#ffffff;"><strong><span style="color:#313140;font-size:12pt;">6.3 Link your Speakede Account with Third-Party Account</span></strong></h6>
                    <p style="color:#ffffff;background-color:#ffffff;"><span style="color:#515164;font-size:10.5pt;">As part of the functionality of the Speakede Platform, you may link your Speakede Account with Third-Party Accounts, by either: (i) providing your Third-Party Account login information to Speakede through the Speakede Platform; or (ii) allowing Speakede to access your Third-Party Account, as permitted under the applicable terms and conditions that govern your use of such Third-Party Account. You represent that you are entitled to disclose your Third-Party Account login information to Speakede and/or grant Speakede access to your Third-Party Account (including, but not limited to, for use by Speakede for the purposes described herein), without breach by you of any of the terms and conditions that govern your use of the applicable Third-Party Account and without obligating Speakede to pay any fees or making Speakede subject to any usage limitations imposed by such third-party service providers. By granting Speakede access to any Third-Party Accounts, you understand that Speakede will access, make available and store (if applicable) any content that you have provided to and stored in your Third-Party Account (&quot;SNS Content&quot;) so that it is available on and through the Speakede Platform via your Speakede Account and Speakede Account profile page. Unless otherwise specified in these Speakede Terms, all SNS Content, if any, will be considered to be Member Content for all purposes of these Speakede Terms.</span></p>
                    <p style="color:#ffffff;background-color:#ffffff;"><span style="color:#515164;font-size:10.5pt;">If you choose to link Third-Party Accounts with your Speakede Account, subject to the privacy settings that you have selected at such Third-Party Accounts, some of the information that you provided to us from the linking of your Third-Party Accounts might be available on and through the Speakede Platform via your Speakede Account and Speakede Account profile page. You have the ability to disable the connection between your Speakede Account and your Third-Party Accounts at any time by accessing the &quot;Settings&quot; section of the Sites or Applications. If you disable the connection between your Speakede Account and your Third</span></p>
                    <p style="color:#ffffff;background-color:#ffffff;"><br></p>
                    <p><br></p>
                    <p><br></p>
                </div>
            </div>
            <!-- Course List Wrapper End -->

        </div>
    </div>
    <!-- Course List End -->


@endsection
